FROM jenkins/ssh-agent:jdk17

# COPY --chown=jenkins mykey "${JENKINS_AGENT_HOME}"/.ssh/mykey
USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-pytest && \
    rm -rf /var/lib/apt/lists/*

RUN python3 --version
RUN pip3 --version
RUN pytest --version

